### ISSUE TITLE
Firefox 113 (Nightly) supports animated AVIF, 7TV site claims it doesn't

### ISSUE THREAD

**Issue by CounterPillow** [SevenTV/Website#967]
Hot fresh off the presses, Firefox enabled animated AVIF support and is allowing it to pass into stable for 113.0: https://bugzilla.mozilla.org/show_bug.cgi?id=1825580

Using Firefox 113 (Nightly) right now confirms [that animated AVIF images work now](https://cdn.7tv.app/emote/642dc2de149264bdac07dd79/4x.avif), but the 7TV website still claims it doesn't.
![image](https://user-images.githubusercontent.com/308818/230210451-2030ed0b-4a45-4e37-8db9-63703a2047c1.png)

**Comment by AnatoleAM** [comment]
Firefox made a botched implementation of AVIF; by adding support for static images only, meaning that the browser reported to applications that the format is supported, even though it really wasn't. This means standard support detection mechanisms, such as `<picture>` tags, would have no use since it would still be rendered, albeit a static image.

That gave us no choice besides manually blacklisting Firefox user agents, we'll have to enable it once it's fully supported into the stable release.

**Comment by CounterPillow** [comment]
You can change this check already since it's in beta and will end up in stable for 113, no need to wait for the stable release, your change will be the same either way:

https://github.com/SevenTV/Website/blob/7cb35f1dd0b7467c30d8b48b8acf8b4f75673a01/src/store/actor.ts#L60

similar to chrome except I suppose `"Firefox"` and `>= 113`.

**Comment by CounterPillow** [comment]
Firefox 113 is out now.
